# Screen
SCREEN_SIZE = 2000, 900

# CAR
CAR_SPEED = 100
DRAW_SENSORS = True
SENSORS_NUMBER = 5
SENSOR_LENGTH = 200
SENSOR_WIDTH = 2

# Collision types
CAR_COLLISION_TYPE = 1
TRACK_COLLISION_TYPE = 0
SENSOR_COLLISION_TYPE = 2
