# Screen
SCREEN_SIZE = 2000, 900

# CAR
CAR_SPEED = 100
DRAW_SENSORS = True
SENSORS_NUMBER = 5
SENSOR_LENGTH = 5
SENSOR_WIDTH = 2
NUMBER_OF_CARS = 50

# Collision types
CAR_COLLISION_TYPE = 1
TRACK_COLLISION_TYPE = 0
SENSOR_COLLISION_TYPE = 2
CHECKPOINT_COLLISION_TYPE = 3

# TRACK
TRACK_CHOICE = 2
SHOW_CHECKPOINTS = True
